# Generated by Django 5.2 on 2025-10-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
