# Generated by Django 5.2 on 2025-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_pedido_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
