# Generated by Django 5.2 on 2025-11-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_calificacion_aprobado'),
        ('usuarios', '0011_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedido'},
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
    ]
