# Generated by Django 5.2 on 2025-11-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_calificacion_servicio'),
        ('usuarios', '0012_alter_pedidoitem_options_pedidoitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reemplazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('devolucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reemplazo', to='usuarios.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Reemplazo',
                'verbose_name_plural': 'Reemplazos',
            },
        ),
    ]
