# Generated by Django 5.2 on 2025-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_reemplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/', verbose_name='Foto 3'),
        ),
    ]
