# Generated by Django 5.2 on 2025-11-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_devolucion_foto1_alter_devolucion_foto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='seleccionada',
            field=models.BooleanField(default=False, verbose_name='Seleccionada por el usuario'),
        ),
    ]
