# Generated by Django 5.2 on 2025-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_devolucion_seleccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='unidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidad del producto'),
        ),
    ]
