# Generated by Django 5.2 on 2025-11-17 16:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_devolucion_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='foto1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto1'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='foto2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto2'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='foto3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto3'),
        ),
    ]
