# Generated by Django 5.2 on 2025-11-18 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_historialdevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='usuarios.pedidoitem'),
        ),
    ]
