# Generated by Django 5.2 on 2025-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
