# Generated by Django 5.2 on 2025-11-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_fecha_caducidad_and_more'),
        ('usuarios', '0021_devolucion_lote_pedidoitem_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.lote'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.lote'),
        ),
    ]
