# Generated by Django 5.2 on 2025-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_devolucion_lote_alter_pedidoitem_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='codigo_lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
