# Generated by Django 5.2 on 2025-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
