# Generated by Django 5.2 on 2025-09-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
