# Generated by Django 5.2 on 2025-11-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_calificacion_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='productos.producto'),
        ),
    ]
