# Generated by Django 5.2 on 2025-11-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_calificacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='productos.servicio'),
        ),
    ]
