# Generated by Django 5.2 on 2025-11-16 03:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_calificacion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgProduc',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
