# Generated by Django 5.2 on 2025-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
